### PR TITLE
Use frequency to improve layout

### PR DESCRIPTION
**Pull request by fmannhardt**
This feature adds two parameters that allow to influence the GraphViz layout using frequency information from the process map.

Before:
image

With  `layout_edge_weight = TRUE`:
image

With `layout_edge_cutoff = 0.01`:
image

The default parameters retain the current behaviour since for some maps (like the simple one above) this might not have a very good effect. But for more complex one this can help retain the "process highway" in focus. Compare the following:

```
process_map(sepsis %>% filter_activity(c("LacticAcid", "CRP", "Leucocytes", "Return ER",
                      "IV Liquid", "IV Antibiotics"), reverse = T), layout_edge_weight = TRUE, layout_edge_cutoff = 0.02)
```
image

```
process_map(sepsis %>% filter_activity(c("LacticAcid", "CRP", "Leucocytes", "Return ER",
                      "IV Liquid", "IV Antibiotics"), reverse = T))
```
image

### CODE REVIEW

**Comment by fmannhardt** [comment]
One issue with this PR is that it uses a hack to get the GraphViz attributes to the edges since DiagrammeR does not support them. Already opened a issue there:
https://github.com/rich-iannone/DiagrammeR/issues/360

**Comment by gertjanssenswillen** [comment]
Perfect, I have a look early next week.

**Comment by fmannhardt** [comment]
Maybe it need some tweaks to get good defaults. In some cases it looks better but depends a bit. So maybe the weights should be somehow scaled.

--
Felix

________________________________

**Comment by gertjanssenswillen** [comment]
Looks fine, just fixed a type in the docs. 

Am I correct when saying that the len and decorate variables are used by GraphViz, len to decrease the lenght of frequent edges? Whats the working behind decorate? 
Am I correct that decorate doesn't actually removes edges, just "adds them later"?

As for defaults, it seems that some (infrequent) activities are placed in awkward places. Maybe you know some other attributes that can be used to tweak this? I'll be having a more thorough look at the graphviz documentations when I have time. 

With respect to arguments, maybe we could clean this up a bit? Together with fixed_node_pos there are now 3 arguments related to layout, maybe we could do sth similar like the functions for type, making a "layout()" function? 
Relatedly, whats the relations between the fixed node positions and the weighted version? Intuitively I expect both methods to be mutually exclusive, is that right?

**Comment by fmannhardt** [comment]
> Am I correct when saying that the len and decorate variables are used by GraphViz, len to decrease the lenght of frequent edges? Whats the working behind decorate?
> Am I correct that decorate doesn't actually removes edges, just "adds them later"?

Using `len` and `decorate` is just a workaround as I am not able to directly set the attributes `weight` and `constraint`. This should be changed as soon as this is fixed in DiagrammeR (if they fix it). 

> As for defaults, it seems that some (infrequent) activities are placed in awkward places. Maybe you know some other attributes that can be used to tweak this? I'll be having a more thorough look at the graphviz documentations when I have time.

Yes, I think mainly when using the cutoff parameter since that turns ignores certain edges with respect to the layout. Maybe, we should not apply the cutoff parameter when it would cutoff all the edges for a single activity. So, we would always keep the most frequent edge to be considered for layout. This would avoid weird positions for infrequent activities and still ignore infrequent edges.

> With respect to arguments, maybe we could clean this up a bit? Together with fixed_node_pos there are now 3 arguments related to layout, maybe we could do sth similar like the functions for type, making a "layout()" function?

Sounds very good. Would be great to keep backwards compatibility somehow.

> Relatedly, whats the relations between the fixed node positions and the weighted version? Intuitively I expect both methods to be mutually exclusive, is that right?

No, it can be both applied together.

**Comment by gertjanssenswillen** [comment]
Allright. I'll commit the changes for a layout() function in the coming days. Backward-compatibility should not be a problem.

**Comment by gertjanssenswillen** [comment]
> Relatedly, whats the relations between the fixed node positions and the weighted version? Intuitively I expect both methods to be mutually exclusive, is that right?
> 
> No, it can be both applied together.

In that case, it will take the fixed position, and ignore the layour paramters, am I right? Or is there an effect on the edges?

**Comment by fmannhardt** [comment]
Oh, I think I misunderstood. Don't know about the relation between both parameters. Could be that the edges are still routed according to the weights.

--
Felix
________________________________

**Comment by gertjanssenswillen** [comment]
I tried some test with the fixed example of patients, adjusting the other paramters didn't make any difference. Not really a problem, just good to know and maybe should be put in the manual. Might also be different when in the end the parameters are used for weight and constraint instead of len and decorate.

**Comment by gertjanssenswillen** [comment]
I created a function layout_pm() which can be used to set the argument layout in process_map. (layout as a function had many conflicts with other packages). It currently contains the three parameters. The fixed_node_pos is retained for backward compatibility but will throw a warning if used directly and not via layout_pm().

**Comment by fmannhardt** [comment]
I fixed the documentation and implemented the idea mentioned above. This improves the layout a bit when there are infrequent activities. Like in sepsis here:

`process_map(edeaR::filter_trace_frequency(sepsis, percentage = 0.2), layout = layout_pm(edge_cutoff = 0.1))`

Rplot

**Comment by fmannhardt** [comment]
From my side this could be merged now.

**Pull request merged**
