### PR TITLE
Added 'color_vector' parameter to dotted chart

### PR DESCRIPTION
**Pull request by jgonzale**
So as to produce coherent plot coloring across bupaR, I added the parameter 'color_vector' to the 'dotted_chart', that can override the default hard-coded coloring.

### CODE REVIEW

**Comment by gertjanssenswillen** [comment]
Thx for the contribution. It's good to have this option. 

The color_vector arguments expects a vector of colors/hex/rgb-values, am I right? So it will have to have exactly the same number of values as there are activities in the plot?

The main other bupaR plot where colors can be customized is the trace explorer, but here, you can specify a scale function (for example any ggplot or ggthemes color scale function). 

Preferably, I think we should have the same syntax as this, if you agree? Or are there any other functions in bupaR which likewise expect specific color vectors as in your suggestion, that I am missing? 

Also, while I do certainly welcome pull requests, for future reference: do not modify the Description file to avoid possible conflicts in version and so one.

**Comment by jgonzale** [comment]
Hi @gertjanssenswillen, thanks for being positive to pull request.

You're right, the `color_vector` requires a vector of RGB values, same size of activities in the plot. I totally agree on having the very same syntax of the `trace_explorer`, but I didn't want to break the internals of the `dotted_chart` (i.e. the `color_vector`). Should I do this modification?

It will be useful to have the possibility of adding to those `bupaR` functions that produce "activity-based" plots to have the possibility of tune the colors, but actually I haven't explored which of them are the candidates, sorry.

Take note of not modifying the DESCRIPTION file.

BR,

**Comment by gertjanssenswillen** [comment]
If you have time to do the modification as in trace_explorer, feel free. I don't see a problem in changing the internal working, and the default colours are allowed to change. I'm not sure however what the default scale should be (ideally something with enough values and easy to interprate), but that default can be changed afterwards.

**Comment by jgonzale** [comment]
I've touching here and there on how to modify the `dotted_chart` to be coherent with the `trace_explorer` semantics for coloring. Actually I have a version right now which properly works using a `scale_fill`.

But now, a question arises. In my opinion, using this interface (the scale function family) you are exposing some internals of the `ggplot` used in those `bupaR` functions (for example, you need to provide the `aesthetics` on how to paint the traces in `trace_explorer`). Wouldn't be more useful to provide just the color palette (i.e. a color vector as I proposed in my first version), and the let the `dotted_chart` and `trace_explorer` functions properly manipulate it to present the information?

BR,

**Comment by gertjanssenswillen** [comment]
I don't see the problem with directly using the scale functions. The advantage is that we do not need to take care of color scales, checking if there right number of colors are there, etc. Do you have any thoughts on this @fmannhardt ?

**Comment by fmannhardt** [comment]
I think as well a function is nicer than the palette. Note that you can also write your own function providing a scale which gives more flexibility. (Sorry for the really late answer)

**Comment by jgonzale** [comment]
Ok @gertjanssenswillen, @fmannhardt I now understand the specificities of the scale functions. I just pushed the version using the `scale_fill` parameter on the `dotted_chart` function, in case you want to merge them.

Best regards,

**Pull request closed without merging**
